# Kbuild fragment (core built-in, test as loadable module)
obj-y += mkring.o
obj-y += init_mk.o
obj-y += mkring_demux.o
obj-m += mkring_test.o
obj-m += mkring_container_bridge.o
obj-m += mkring_stream_bridge.o
